name: Hourly Trading Algo

on:
  schedule:
    - cron: '0 * * * *' # Runs exactly at minute 00 of every hour
  workflow_dispatch: # Allows you to manually click a button to test it!

jobs:
  trade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Libraries
        run: pip install pandas numpy yfinance pandas-ta xgboost requests pytz scikit-learn ccxt

      - name: Run Algorithm
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
