name: Hourly Trading Algo

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  trade:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Notice we added 'matplotlib' to draw the chart!
      - name: Install Libraries
        run: pip install pandas numpy yfinance pandas-ta xgboost requests pytz scikit-learn ccxt matplotlib

      - name: Run Algorithm
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
          BINANCE_SECRET: ${{ secrets.BINANCE_SECRET }}
        run: python main.py

     # This saves the new log file back to your GitHub repository forever
      - name: Commit and Push Trade Log
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add trade_log.csv
          # We use || echo to prevent the server from crashing if there are no new trades
          git commit -m "Auto-updated trade_log.csv" || echo "No changes to commit"
          git pull --rebase
          
          git push
